import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased w-screen h-screen overflow-y-scroll">
        <div className="max-w-screen-2xl mx-auto flex flex-col gap-4">
          {children}
        </div>
      </body>
    </html>
  );
}
